apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: team-beta
patches:
  - target:
      kind: RoleBinding
      name: team-namespace-edit
    patch: |-
      - op: replace
        path: /subjects/0/name
        value: "team-beta-engineers"
  - target:
      kind: ResourceQuota
      name: namespace-compute-quota
    patch: |-
      - op: replace
        path: /spec/hard/requests.cpu
        value: "8"        # más CPU para el equipo de backend
      - op: replace
        path: /spec/hard/limits.cpu
        value: "16"
