apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parksmap-helm-admin
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/ziroch/demo.git  # Tu repo
    targetRevision: main
    path: helm/parksmap
    helm:
      parameters:
        - name: replicaCount
          value: "1"
  destination:
    server: https://kubernetes.default.svc
    namespace: workshop-admin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
