apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - networkpolicy-deny-all.yaml
  - resourcequota.yaml
  - limitrange.yaml
  - rolebinding-team.yaml
commonLabels:
  managed-by: openshift-gitops
  policy-baseline: "true"
