apiVersion: v1
kind: LimitRange
metadata:
  name: namespace-container-limits
  labels:
    policy-type: baseline
    managed-by: argocd
spec:
  limits:
  - type: Container
    # Defaults aplicados si el container no especifica requests/limits
    default:
      cpu: 200m
      memory: 256Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    # Rango permitido para requests y limits
    min:
      cpu: 50m
      memory: 64Mi
    max:
      cpu: "4"
      memory: 4Gi
  - type: Pod
    max:
      cpu: "8"
      memory: 8Gi
  - type: PersistentVolumeClaim
    max:
      storage: 50Gi
    min:
      storage: 1Gi
