apiVersion: v1
kind: Service
metadata:
  name: mongodb-nationalparks
  labels:
    app: national-parks-app
    component: mongodb
spec:
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
  selector:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/part-of: national-parks-app
    deployment: mongodb-nationalparks
---
apiVersion: v1
kind: Service
metadata:
  name: nationalparks
  labels:
    app: national-parks-app
    component: backend
    # Esta etiqueta permite que el frontend encuentre el backend automáticamente
    type: parksmap-backend
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: national-parks-app
    component: backend
    deployment: nationalparks
---
apiVersion: v1
kind: Service
metadata:
  name: parksmap
  labels:
    app: national-parks-app
    component: parksmap
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: national-parks-app
    component: parksmap
    deployment: parksmap
