apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: parksmap
  labels:
    app: national-parks-app
    component: parksmap
spec:
  path: /
  to:
    kind: Service
    name: parksmap
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
