resources:
  - ../../base

# Esto añadirá un prefijo a todos los recursos para diferenciar el entorno
namePrefix: dev-

# Configuración para que namePrefix actualice las referencias en Routes
configurations:
  - kustomizeconfig.yaml

# Aquí es donde los alumnos practicarán cambiar la imagen en el Lab D
images:
  - name: quay.io/openshiftroadshow/parksmap
    newTag: "1.3.0"
